# golangci-lint configuration
# See https://golangci-lint.run/usage/configuration/ for available options

version: "2"

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - testdata

linters:
  enable:
    # Enabled by default linters:
    - errcheck     # Checks for unchecked errors
    - govet        # Reports suspicious constructs
    - ineffassign  # Detects ineffectual assignments
    - staticcheck  # Go static analysis (includes gosimple and stylecheck)
    - unused       # Checks for unused code

    # Additional recommended linters:
    - misspell     # Finds commonly misspelled words
    - revive       # Fast, configurable, extensible, flexible linter
    - unparam      # Reports unused function parameters
    - unconvert    # Removes unnecessary type conversions
    - gosec        # Security-focused linter
    - gocritic     # Provides diagnostics that check for bugs, performance, and style issues
    - gocyclo      # Computes and checks cyclomatic complexity
    - dupl         # Code clone detection
    - bodyclose    # Checks whether HTTP response body is closed successfully
    - nilerr       # Finds code that returns nil even if it checks that error is not nil
    - prealloc     # Finds slice declarations that could potentially be preallocated
    - whitespace   # Detects leading and trailing whitespace
    - goconst      # Finds repeated strings that could be constants
    - goprintffuncname # Checks that printf-like functions are named with f at the end

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false

  govet:
    enable-all: true

  gocyclo:
    min-complexity: 15

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  gosec:
    excludes:
      - G204  # Audit use of command execution - we need this for terminus CLI

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - gosec
        - goconst
